export nonInteractive="YES"
BSDINSTALL_LOG="./bsdinstall.log"
DISTRIBUTIONS="base.txz kernel.txz doc.txz"
ASSUME_ALWAYS_YES=yes
#!/bin/sh
sysrc hostname="grafana-bsd"
sysrc local_unbound_enable=YES
sysrc ntpd_enable=YES
sysrc dumpdev=YES
sysrc zfs_enable=YES
sysrc ifconfig_vtnet0=DHCP
pkg install apache24 py27-graphite-web www/mod_wsgi4 www/grafana2
sysrc grafana2_enable="YES"
sysrc carbon_enable="YES"
sysrc apache24_enable="YES"

# create netcrk & root users
# configure apache24 vhosts

